config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "lists#index"

  resources :lists do
    member do
      post :done
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  #驗證：欄位必須有值
  validates_presence_of :title, :date

  #allow_blank: :true 開啟允許空白
  validates :description, :presence => true, :allow_blank => true

  # 驗證：長度 20 個字符
  validates :title, length: {maximum: 20}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :find_list, :only => [:show, :edit, :update, :destroy, :done]

  def index
    # 依到期日 (due_date) 近到遠，取得 todos
    @lists = List.order(date: :asc)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_url, :notice => "成功新增一筆代辦事項！"
    else
      render :action => :new
    end
  end

  def update
    if @list.update_attributes(list_params)
      redirect_to list_path(@list), :notice => "更新成功！"
    else
      render :edit
    end
  end

  def destroy
    if Time.current < @list.date
      @list.destroy
      flash[:notice] = "已刪除！"
    else
      flash[:notice] = "超過期限，無法刪除！"
    end

    redirect_to lists_url
  end

  def done
    @list.update(done: !(@list.done))
  end

  private

  def list_params
    params.require(:list).permit(:title, :date, :description)
  end

  def find_list
    @list = List.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My To Do List</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
      *{
        box-sizing: border-box;
      }

    </style>
  </head>

  <body>
    <p><%= flash[:notice] %></p>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<% if @list.errors.present? %>
  <ul>
    <% @list.errors.each do |error, message| %>
      <li> <%= "#{error.capitalize} #{message}" %></li>
    <% end %>
  </ul>
<% end %>

<div class="form-container text-left">
  <div class="col-md-8 col-md-offset-2">
    <%= form_for @list do |f| %>
      <div class="form-group">
        <%= f.label :title, "標題" %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :date, "到期日" %>
        <%= f.date_select :date, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :description, "備註" %>
        <%= f.text_area :description, class: "form-control" %>
      </div>

      <div class = "button pull-right">
        <%= f.submit %>
        <%= link_to '回到上一頁', :back, class: "btn btn-sm btn-default" %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/edit.html.erb
<%= render :partial => "form" %>

app/views/lists/index.html.erb
<div class="container text-center">
  <div class="col-md-12">
    <h1>To Do List</h1>
    <p class = "button pull-right">
      <button type="button" class="btn btn-default btn-sm">
        <%= link_to "<span class='glyphicon glyphicon-plus'></span> 新增".html_safe, new_list_path %>
      </button>
    </p>

    <table class="table table-striped table-condensed">
      <tr>
        <td> </td>
        <td>代辦事項</td>
        <td>到期日</td>
        <td>檢視</td>
        <td>編輯</td>
        <td>刪除</td>
      </tr>
      <% @lists.each do |list| %>
        <tr>
          <td>
            <%= check_box_tag :done, true, list.done, data: {url: done_list_path(list), method: :post, remote: true} %>
          </td>
          <td><%= list.title %></td>
          <td><%= list.date %></td>
          <td><%= link_to "<span class='glyphicon glyphicon-eye-open'></span>".html_safe, list_path(list) %></td>
          <td><%= link_to "<span class='glyphicon glyphicon-edit'></span>".html_safe, edit_list_path(list) %></td>
          <td><%= link_to "<span class='glyphicon glyphicon-trash'></span>".html_safe, list_path(list), method: :delete, data:{ confirm: "Are you sure?" } %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/lists/new.html.erb
<%= render :partial => "form" %>

app/views/lists/show.html.erb
<div class = "form-container">
  <div class="col-md-8 col-md-offset-2">
    <h2>To Do List</h2>

    <table class="table table-bordered">
      <tr>
        <td>代辦事項</td>
        <td><%= @list.title %></td>
      </tr>
      <tr>
        <td>到期日</td>
        <td><%= @list.date %></td>
      </tr>
      <tr>
        <td>備註</td>
        <td><%= simple_format(@list.description) %></td>
      </tr>
    </table>

    <div class = "button pull-right">
      <%= link_to '回到首頁', lists_path, class: "btn btn-sm btn-default btn-success" %>
    </div>
  </div>
</div>